### ISSUE TITLE
Document KubeOne EKS-D use case

### ISSUE THREAD

**Issue by toschneck** [kubermatic/docs#499] opened 2021-01-19 21:57 UTC
Amzon EKS-D usage with kubeone should also visible in the recent KubeOne Docs.

As quick win, at least a link to the blog entry should be placed
https://www.kubermatic.com/blog/get-started-with-eks-d-at-the-speed-of-light-with-kubermatic-kubeone/

**Comment by xmudrii** [comment] 2021-03-09 14:46
This seems to be a duplicate of #493.
/close

**Closed by xmudrii** 2021-03-09 14:46 UTC
Labels: kind/documentation
